dataset:
  name: cifar10-LT
  kwargs: null

model:
  name: resnet18
  kwargs:
    pretrain

phase: train  # train or test

train:
  num_epoch: 300
  batch_size: 128
  loss: SoftmaxCrossEntropy
  optimizer:
    name: SGD  # class name in torch.optim
    kwargs: null
  lr: 0.1
  lr_scheduler:
    name: StepLR  # class name in torch.optim.lr_scheduler
    kwargs:
      step_size: 150  # epoch step
      gamma: 0.1
  gradient_clip: null  # null or float

test:
  batch_size: 128
  loss: softmax

checkpoint:
  path: checkpoints/
  load_checkpoint: null  # like 'best_model.pt'. if none, no load checkpoint

log:
  path: exp/
  log_interval: 200  # only for train phase
