random_seed: 1314  # null for no seed

dataset:
  name: ImageNet-LT
  kwargs: 
    im: 256

model:
  name: resnet10
  kwargs:
    pretrained: false

test:
  batch_size: 128

feature:
  path: feature/
  cam_layers: 'layer4'  # separate by comma. e.g., 'layer3, layer4'

checkpoint:
  load_checkpoint: 'checkpoints/phase_i/imageNet-LT/default_setting/best_model.pt'
  
